### PR TITLE
Flight display ui + api set up

### PR DESCRIPTION
**Pull request by RanaMohamed6720**
implemented a flight card that displays:
- departure and arrival times, source and destination cities, and flight dates.
- shows the price of the flight.
- includes a "Book" button  and a "Show Details" link to fetch and display more flight legs when clicked.
image

implemented a search filter modal for the available flights which:
- fetches and displays flight results based on selected filters.
- users can filter flights using dropdowns as shown here:
image

I put a set up for api integration with the backend.

### CODE REVIEW

**Comment by OmniaTarek18** [comment]
I can't understand why there are departure city and arrival city ? Didn't he already specify the source and destination or you want to him to be able to change any of the info he already provided.
Note that the both approaches are fine for back-end endpoints.

**Comment by RanaMohamed6720** [comment]
My approach was to enable users to modify their source and destination cities directly without needing to return to the search form and re-enter their details. This enhances flexibility especially in cases where no flights are available for the initially selected cities. By allowing users to explore nearby cities as alternatives they can quickly adjust their travel plans and book a flight from a nearby city to their desired destination.

**Comment by nouranKhalil** [comment]
image
Typically, in other applications, filters are placed on the side for easier access or remain open after being applied. I suggest keeping the filter modal open after the user applies a filter to allow further adjustments without reopening the modal. 

To enhance the experience, you could add a button that displays the number of filtered flights (e.g., "List [X] Flights"). This button would appear after the filter is applied for the first time. When the user presses it, the modal closes, providing a smooth transition to the filtered results.

**Comment by RanaMohamed6720** [comment]
I highly appreciate your opinion but I respectfully disagree.

Most users expect the modal to close immediately after they apply filters. This is the standard and intuitive behavior in most flight booking and e-commerce applications. The workflow is simple: the user applies filters → the modal closes → the updated flight results are displayed. This creates a smooth and predictable experience.

Keeping the modal open might add unnecessary steps. For instance the user would need to click "List [X] Flights" or "Close" after applying filters, which could feel redundant and disrupt the flow.

That said, I value your perspective and will take your suggestion into consideration. I plan to test this approach to see if it indeed improves usability and enhances the overall user experience.

**Comment by nouranKhalil** [comment]
image
I actually did some research before providing my feedback and found that many websites keep the filter options on the same page for faster access, allowing users to modify their selections quickly. I didn’t suggest this approach earlier because I thought it would take additional time to implement. Instead, I proposed my suggestion under the assumption that if a user fills out the form and gets no results, it would be more efficient for them to edit the filters without closing and reopening the modal. However, I still appreciate your point of view, and mine was just an advice based on my findings.

**Pull request merged**
